default-value:
  key-1: 50
  key-2: 50
key-1: value-string
CaseInsensitive: "you get [CaseInsensitive] key value"
nest:
  bool-key: true
  float64-key: 1.234
  int-key: 10
  int-slice-key:
    - 20
    - 30
    - 40
  string-key: "string-value"
  string-slice-key:
    - string-value-1
    - string-value-2
    - string-value-3
#  time-key:
  duration-key-3s: 3s
  duration-key-0.5s: 0.5s
  duration-key-30ms: 30ms
  duration-key-3000ms: 3000ms
env:
  k1: 50
  k2: 50
  k3: 50
deep-nest:
  k11:
    k21:
      k31: value
      k32: value
    k22:
      k31: value
      k32: value
  k12:
    k21:
      k31: value
      k32: value
    k22:
      k31: value
      k32: value
mapping:
  int-key: 10
  string-key: string-value
  int-slice:
    - 10
    - 20
    - 30
  sub:
    int-key: 40